USE [AXDB]
GO
ALTER DATABASE AUDIT SPECIFICATION [AccessPayroll] WITH (STATE = OFF)
DROP DATABASE AUDIT SPECIFICATION [AccessPayroll]

CREATE DATABASE AUDIT SPECIFICATION [AccessPayroll]
FOR SERVER AUDIT [AuditPayrollAccess]
	ADD (SELECT ON OBJECT::[dbo].[SPYPAYROLLDETAILS] BY [db_datareader]),
	ADD (SELECT ON OBJECT::[dbo].SPYWORKERPOSITIONPAYROLL BY [db_datareader]),
	ADD (SELECT ON OBJECT::[dbo].SPYPAYROLLLEDGER BY [db_datareader]),
	ADD (SELECT ON OBJECT::[dbo].SPYBENEFITLEDGER BY [db_datareader])
WITH (STATE = ON)

USE AXDBReporting
GO
CREATE DATABASE AUDIT SPECIFICATION [AccessPayroll]
FOR SERVER AUDIT [AuditPayrollAccess]
	ADD (SELECT ON OBJECT::[dbo].SPYABSENCECONFIGLINE_CR100147 BY [db_datareader]),
	ADD (SELECT ON OBJECT::[dbo].SPYABSENCELEDGER_BENEFITLEDGER_CR100147 BY [db_datareader]),
	ADD (SELECT ON OBJECT::[dbo].SPYABSENCELEDGER_CR100137 BY [db_datareader]),
	ADD (SELECT ON OBJECT::[dbo].SPYABSENCELEDGER_CR100147 BY [db_datareader]),
	ADD (SELECT ON OBJECT::[dbo].SPYABSENCELEDGER_CR100197 BY [db_datareader]),
	ADD (SELECT ON OBJECT::[dbo].SPYABSENCELEDGER_CR100655 BY [db_datareader]),
	ADD (SELECT ON OBJECT::[dbo].SPYBENEFITLEDGER_20200114 BY [db_datareader])
WITH (STATE = ON)
GO


ALTER DATABASE AUDIT SPECIFICATION [AccessContactInfo] WITH (STATE = OFF);
DROP DATABASE AUDIT SPECIFICATION [AccessContactInfo];

CREATE DATABASE AUDIT SPECIFICATION [AccessContactInfo]
FOR SERVER AUDIT [AuditContactInfoAccess]
	ADD (SELECT ON OBJECT::[dbo].LOGISTICSELECTRONICADDRESS BY [db_datareader]),
	ADD (SELECT ON OBJECT::[dbo].HCMPOSITIONDETAIL BY [db_datareader]),
	ADD (SELECT ON OBJECT::[dbo].HCMPERSONPRIVATEDETAILS BY [db_datareader]),
	ADD (SELECT ON OBJECT::[dbo].DIRPARTYTABLE BY [db_datareader]),
	ADD (SELECT ON OBJECT::dbo.INVENTLOCATION BY db_datareader),
	ADD (SELECT ON OBJECT::dbo.PROJFUNDINGSOURCE BY db_datareader),
	ADD (SELECT ON OBJECT::dbo.LOGISTICSPOSTALADDRESS BY db_datareader)
WITH (STATE = ON)
GO


select * from ASSETLOCATION

select OBJECT_NAME(major_id) as tablename,* from sys.sensitivity_classifications order by tablename
go 


ADD SENSITIVITY CLASSIFICATION TO dbo.SPYWORKERPOSITIONPAYROLL.