USE [DBA]
GO


CREATE OR ALTER view [dbo].[pbi_database_size_log_dtl] as
WITH dtl as (
SELECT	D2.INSTANCEFULLNAME,
		D2.LOG_DATE,
		--SUBSTRING(INSTANCEFULLNAME,1, CHARINDEX('\', INSTANCEFULLNAME,1)-1 ) as HostName,
		--SUBSTRING(INSTANCEFULLNAME, CHARINDEX('\', INSTANCEFULLNAME,1) + 1, 15) as InstanceName,
		D2.DATABASENAME,
		USAGETYPE,
		ALLOCATIONTYPE,
		USED_MB,
		USED_MB - (LAG (USED_MB) OVER (PARTITION BY D2.DATABASENAME, USAGETYPE, ALLOCATIONTYPE ORDER BY D2.LOG_DATE)) as Daily_Change_MB,
		CASE WHEN (USED_MB - (LAG (USED_MB) OVER (PARTITION BY D2.DATABASENAME, USAGETYPE, ALLOCATIONTYPE ORDER BY D2.LOG_DATE))) < 0 THEN 0
			ELSE (USED_MB - (LAG (USED_MB) OVER (PARTITION BY D2.DATABASENAME, USAGETYPE, ALLOCATIONTYPE ORDER BY D2.LOG_DATE))) 
		END	as Daily_Change2_MB,
		RESERVED_MB,
		FILEGROUPNAME,
		ROW_NUMBER() OVER (PARTITION BY LOG_DATE, DATABASENAME, USAGETYPE, ALLOCATIONTYPE, FILEGROUPNAME ORDER BY MODIFIED_ON DESC) as rn 
FROM DatabaseSizeLogDetails D2
where D2.LOG_DATE >=  DATEADD(DAY, -60, GETDATE())
)

select * from dtl 
where rn = 1
GO



